# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - npm run dev
  update:astro:
    cmds:
      - npx @astrojs/upgrade
  update:dependencies:
    cmds:
      - npx npm-check-updates -u
      - npm install
